### PR TITLE
fix: add account closure tracking to prevent mainnet refetch (#402)

### LINKED ISSUE #402: Differentiate a deleted account from a reset/streamed account
Currently, if an account doesn't exist locally, we fetch from mainnet when it's referenced in a request.

We take advantage of this for our `resetAccount` and `streamAccount` endpoints - we can delete an account locally to pull afresh from mainnet.

However, when an account is closed, it is deleted from our cache and is thus pulled from mainnet again. This is a confusing experience if you've just closed an account locally that exists on mainnet - the account continues to stick around because we pull from mainnet.

### PR DESCRIPTION
**Pull request by AvhiMaz**
Distinguish between user-initiated closure and reset/stream operations.
   - Add closed_accounts HashSet to SurfnetSvm
   - Check closed accounts before mainnet fetch in retrieval logic
   - Add close_account/unclose_account methods
   - Update reset_account to unclose before reset

  Fixes #402

### CODE REVIEW

**Comment by AvhiMaz** [comment]
@MicaiahReid  hi ser, can you review this pr ? thank you

**Comment by AvhiMaz** [comment]
hi @MicaiahReid, i tried to implement what you said. if you think i'm on the right path, let me know, otherwise you can take it from here. thank you.

File: crates/core/src/surfnet/locker.rs [hunk 1]
```diff
@@ -1685,6 +1719,38 @@ impl SurfnetSvmLocker {
         self.with_svm_reader(|svm_reader| svm_reader.streamed_accounts.clone())
     }
 
+    /// Marks an account as explicitly closed by the user.
+    ///
+    /// Once marked as closed, this account will not be fetched from mainnet even if it doesn't exist
+    /// in the local cache. This prevents closed accounts from being inadvertently restored.
+    pub fn close_account(&self, pubkey: Pubkey) -> SurfpoolResult<()> {
```
Comment (MicaiahReid) [inline crates/core/src/surfnet/locker.rs]: I think we can remove this method, it's not used currently, and I don't think we'll need to

File: crates/core/src/surfnet/locker.rs [hunk 2]
```diff
@@ -340,11 +351,20 @@ impl SurfnetSvmLocker {
             inner: local_results,
         } = self.get_multiple_accounts_local(pubkeys);
 
-        // Collect missing pubkeys (local_results is already in correct order from pubkeys)
+        // Get the closed accounts set
+        let closed_accounts = self.with_svm_reader(|svm_reader| svm_reader.closed_accounts.clone());
```
Comment (MicaiahReid) [inline crates/core/src/surfnet/locker.rs]: I think you can just used your `self. get_closed_accounts()` helper here instead of `with_svm_reader`

File: crates/core/src/surfnet/locker.rs [hunk 3]
```diff
@@ -264,8 +266,16 @@ impl SurfnetSvmLocker {
         let result = self.get_account_local(pubkey);
 
         if result.inner.is_none() {
-            let remote_account = client.get_account(pubkey, commitment_config).await?;
-            Ok(result.with_new_value(remote_account))
+            // Check if the account has been explicitly closed - if so, don't fetch from remote
+            let is_closed =
+                self.with_svm_reader(|svm_reader| svm_reader.closed_accounts.contains(pubkey));
```
Comment (MicaiahReid) [inline crates/core/src/surfnet/locker.rs]: I think you can just used your `self. get_closed_accounts()` helper here instead of `with_svm_reader`

**Comment by AvhiMaz** [comment]
> Awesome work, thanks @AvhiMaz!!

you can run the ci/cd. if there are any errors, i’m ready to fix them 🫡

**Comment by AvhiMaz** [comment]
@MicaiahReid there was a formatting issue. i rebased with the main branch and pushed it. hopefully the issue is resolved now.

**Comment by lgalabru** [comment]
thanks @AvhiMaz ! do you think you could refresh your branch with latest `main`? we'll merge your work right after, thank you for your contribution!

**Comment by AvhiMaz** [comment]
hi @lgalabru
- synced the code with main branch
- fixed the conflict
- and applied formatting

ig its ready to merge, thanks!
